# Generated by Django 2.2 on 2019-04-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='test1', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password_hash',
            field=models.CharField(default='test1', max_length=60),
            preserve_default=False,
        ),
    ]
