# Generated by Django 2.0.3 on 2019-04-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190407_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='locations',
            field=models.ManyToManyField(blank=True, through='users.UserLocations', to='locations.Locations'),
        ),
    ]
