# Generated by Django 2.0.3 on 2019-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190407_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='user3', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
