# Generated by Django 2.0.3 on 2019-04-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_url',
            field=models.CharField(default='', max_length=120),
        ),
    ]
