# Generated by Django 2.0.3 on 2019-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_locations_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
